// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQQhLyyafyUm1GD-0_XvNZAtGRHDrKBc',
    appId: '1:953657246968:web:40573f29e4ff08db17e70d',
    messagingSenderId: '953657246968',
    projectId: 'tinostaguta',
    authDomain: 'tinostaguta.firebaseapp.com',
    storageBucket: 'tinostaguta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJlOHCXTbtd1cba0PARmVHiGGdTUULS4',
    appId: '1:953657246968:android:2be5a22fbfda634417e70d',
    messagingSenderId: '953657246968',
    projectId: 'tinostaguta',
    storageBucket: 'tinostaguta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8M8pZUSBC-Ar0uL-ZcN92vBVvtoQswE',
    appId: '1:953657246968:ios:6d69490f47fd573817e70d',
    messagingSenderId: '953657246968',
    projectId: 'tinostaguta',
    storageBucket: 'tinostaguta.firebasestorage.app',
    iosClientId: '953657246968-jmqupe768l4sdn1o20eenvbn69r8ljge.apps.googleusercontent.com',
    iosBundleId: 'com.example.transfarmation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8M8pZUSBC-Ar0uL-ZcN92vBVvtoQswE',
    appId: '1:953657246968:ios:6d69490f47fd573817e70d',
    messagingSenderId: '953657246968',
    projectId: 'tinostaguta',
    storageBucket: 'tinostaguta.firebasestorage.app',
    iosClientId: '953657246968-jmqupe768l4sdn1o20eenvbn69r8ljge.apps.googleusercontent.com',
    iosBundleId: 'com.example.transfarmation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWXBvf_T1d5Joz4BIyCurBS4sKH3Wp48c',
    appId: '1:953657246968:web:13424943ebb76e3917e70d',
    messagingSenderId: '953657246968',
    projectId: 'tinostaguta',
    authDomain: 'tinostaguta.firebaseapp.com',
    storageBucket: 'tinostaguta.firebasestorage.app',
  );
}
