import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/commodity.dart';

final commoditiesProvider = Provider<List<Commodity>>((ref) {
  return [
    Commodity(
      id: '1',
      name: 'White Maize',
      category: 'grain',
      unit: 'per tonne',
      currentPrice: 390,
      previousPrice: 360,
      history: const [
        PricePoint(month: 'Jul', price: 340),
        PricePoint(month: 'Aug', price: 350),
        PricePoint(month: 'Sep', price: 365),
        PricePoint(month: 'Oct', price: 370),
        PricePoint(month: 'Nov', price: 355),
        PricePoint(month: 'Dec', price: 345),
        PricePoint(month: 'Jan', price: 350),
        PricePoint(month: 'Feb', price: 360),
        PricePoint(month: 'Mar', price: 370),
        PricePoint(month: 'Apr', price: 380),
        PricePoint(month: 'May', price: 385),
        PricePoint(month: 'Jun', price: 390),
      ],
      listings: const [
        MarketListing(id: 'ml1', buyerName: 'GMB (Grain Marketing Board)', location: 'Nationwide', priceOffered: 390, terms: '30-day', type: 'gmb'),
        MarketListing(id: 'ml2', buyerName: 'National Foods', location: 'Harare', priceOffered: 400, terms: 'cash', type: 'private'),
        MarketListing(id: 'ml3', buyerName: 'Mbare Musika Traders', location: 'Harare', priceOffered: 410, terms: 'cash', type: 'auction'),
      ],
    ),
    Commodity(
      id: '2',
      name: 'Soya Beans',
      category: 'oilseed',
      unit: 'per tonne',
      currentPrice: 680,
      previousPrice: 700,
      history: const [
        PricePoint(month: 'Jul', price: 620),
        PricePoint(month: 'Aug', price: 640),
        PricePoint(month: 'Sep', price: 660),
        PricePoint(month: 'Oct', price: 680),
        PricePoint(month: 'Nov', price: 700),
        PricePoint(month: 'Dec', price: 710),
        PricePoint(month: 'Jan', price: 720),
        PricePoint(month: 'Feb', price: 715),
        PricePoint(month: 'Mar', price: 710),
        PricePoint(month: 'Apr', price: 700),
        PricePoint(month: 'May', price: 690),
        PricePoint(month: 'Jun', price: 680),
      ],
      listings: const [
        MarketListing(id: 'ml4', buyerName: 'Surface Wilmar', location: 'Harare', priceOffered: 690, terms: 'cash', type: 'private'),
        MarketListing(id: 'ml5', buyerName: 'Olivine Industries', location: 'Mutare', priceOffered: 680, terms: '14-day', type: 'private'),
      ],
    ),
    Commodity(
      id: '3',
      name: 'Tobacco (Flue-cured)',
      category: 'cash_crop',
      unit: 'per kg',
      currentPrice: 3.80,
      previousPrice: 3.50,
      history: const [
        PricePoint(month: 'Jul', price: 3.20),
        PricePoint(month: 'Aug', price: 3.25),
        PricePoint(month: 'Sep', price: 3.30),
        PricePoint(month: 'Oct', price: 3.35),
        PricePoint(month: 'Nov', price: 3.40),
        PricePoint(month: 'Dec', price: 3.45),
        PricePoint(month: 'Jan', price: 3.50),
        PricePoint(month: 'Feb', price: 3.55),
        PricePoint(month: 'Mar', price: 3.60),
        PricePoint(month: 'Apr', price: 3.70),
        PricePoint(month: 'May', price: 3.75),
        PricePoint(month: 'Jun', price: 3.80),
      ],
      listings: const [
        MarketListing(id: 'ml6', buyerName: 'TIMB Auction Floors', location: 'Harare', priceOffered: 3.80, terms: 'auction', type: 'auction'),
        MarketListing(id: 'ml7', buyerName: 'Mashonaland Tobacco Co', location: 'Harare', priceOffered: 3.90, terms: 'contract', type: 'export'),
      ],
    ),
    Commodity(
      id: '4',
      name: 'Groundnuts',
      category: 'oilseed',
      unit: 'per tonne',
      currentPrice: 950,
      previousPrice: 900,
      history: const [
        PricePoint(month: 'Jul', price: 850),
        PricePoint(month: 'Aug', price: 860),
        PricePoint(month: 'Sep', price: 870),
        PricePoint(month: 'Oct', price: 880),
        PricePoint(month: 'Nov', price: 890),
        PricePoint(month: 'Dec', price: 900),
        PricePoint(month: 'Jan', price: 910),
        PricePoint(month: 'Feb', price: 920),
        PricePoint(month: 'Mar', price: 930),
        PricePoint(month: 'Apr', price: 940),
        PricePoint(month: 'May', price: 945),
        PricePoint(month: 'Jun', price: 950),
      ],
      listings: const [
        MarketListing(id: 'ml8', buyerName: 'Mbare Musika', location: 'Harare', priceOffered: 960, terms: 'cash', type: 'auction'),
      ],
    ),
    Commodity(
      id: '5',
      name: 'Cattle (Live)',
      category: 'livestock',
      unit: 'per head',
      currentPrice: 800,
      previousPrice: 750,
      history: const [
        PricePoint(month: 'Jul', price: 700),
        PricePoint(month: 'Aug', price: 710),
        PricePoint(month: 'Sep', price: 720),
        PricePoint(month: 'Oct', price: 730),
        PricePoint(month: 'Nov', price: 740),
        PricePoint(month: 'Dec', price: 750),
        PricePoint(month: 'Jan', price: 760),
        PricePoint(month: 'Feb', price: 770),
        PricePoint(month: 'Mar', price: 780),
        PricePoint(month: 'Apr', price: 790),
        PricePoint(month: 'May', price: 795),
        PricePoint(month: 'Jun', price: 800),
      ],
      listings: const [
        MarketListing(id: 'ml9', buyerName: 'CSC (Cold Storage Co)', location: 'Bulawayo', priceOffered: 810, terms: '30-day', type: 'private'),
        MarketListing(id: 'ml10', buyerName: 'Koala Park Abattoir', location: 'Harare', priceOffered: 820, terms: 'cash', type: 'private'),
      ],
    ),
    Commodity(
      id: '6',
      name: 'Tomatoes',
      category: 'vegetable',
      unit: 'per crate',
      currentPrice: 15,
      previousPrice: 18,
      history: const [
        PricePoint(month: 'Jul', price: 25),
        PricePoint(month: 'Aug', price: 22),
        PricePoint(month: 'Sep', price: 20),
        PricePoint(month: 'Oct', price: 18),
        PricePoint(month: 'Nov', price: 16),
        PricePoint(month: 'Dec', price: 14),
        PricePoint(month: 'Jan', price: 12),
        PricePoint(month: 'Feb', price: 14),
        PricePoint(month: 'Mar', price: 16),
        PricePoint(month: 'Apr', price: 18),
        PricePoint(month: 'May', price: 17),
        PricePoint(month: 'Jun', price: 15),
      ],
    ),
    Commodity(
      id: '7',
      name: 'Cotton',
      category: 'cash_crop',
      unit: 'per kg',
      currentPrice: 0.85,
      previousPrice: 0.80,
      history: const [
        PricePoint(month: 'Jul', price: 0.70),
        PricePoint(month: 'Aug', price: 0.72),
        PricePoint(month: 'Sep', price: 0.74),
        PricePoint(month: 'Oct', price: 0.76),
        PricePoint(month: 'Nov', price: 0.78),
        PricePoint(month: 'Dec', price: 0.80),
        PricePoint(month: 'Jan', price: 0.80),
        PricePoint(month: 'Feb', price: 0.82),
        PricePoint(month: 'Mar', price: 0.83),
        PricePoint(month: 'Apr', price: 0.84),
        PricePoint(month: 'May', price: 0.84),
        PricePoint(month: 'Jun', price: 0.85),
      ],
      listings: const [
        MarketListing(id: 'ml11', buyerName: 'Cottco', location: 'Nationwide', priceOffered: 0.85, terms: 'contract', type: 'private'),
      ],
    ),
  ];
});

// --- Filtered by category ---
final selectedCategoryProvider = StateProvider<String?>((ref) => null);

final filteredCommoditiesProvider = Provider<List<Commodity>>((ref) {
  final all = ref.watch(commoditiesProvider);
  final cat = ref.watch(selectedCategoryProvider);
  if (cat == null) return all;
  return all.where((c) => c.category == cat).toList();
});
